package net.pixelatedd3v.bossmessenger.service.feedback;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

	/**
	 * @return returns com.pixelatedev.bossmessenger.feedback.ArrayOfPoll
	 */
	@WebMethod(operationName = "GetAvailablePolls", action = "http://pixelatedev.com/bossmessenger/feedback/GetAvailablePolls")
	@WebResult(name = "GetAvailablePollsResult", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback")
	@RequestWrapper(localName = "GetAvailablePolls", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback", className = "com.pixelatedev.bossmessenger.feedback.GetAvailablePolls")
	@ResponseWrapper(localName = "GetAvailablePollsResponse", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback", className = "com.pixelatedev.bossmessenger.feedback.GetAvailablePollsResponse")
	public ArrayOfPoll getAvailablePolls();

	/**
	 * @param id
	 * @return returns com.pixelatedev.bossmessenger.feedback.LoadedPoll
	 */
	@WebMethod(operationName = "LoadPoll", action = "http://pixelatedev.com/bossmessenger/feedback/LoadPoll")
	@WebResult(name = "LoadPollResult", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback")
	@RequestWrapper(localName = "LoadPoll", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback", className = "com.pixelatedev.bossmessenger.feedback.LoadPoll")
	@ResponseWrapper(localName = "LoadPollResponse", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback", className = "com.pixelatedev.bossmessenger.feedback.LoadPollResponse")
	public LoadedPoll loadPoll(@WebParam(name = "id", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback") int id);

	/**
	 * @param pollId
	 * @param optionId
	 */
	@WebMethod(operationName = "VoteMultipleChoice", action = "http://pixelatedev.com/bossmessenger/feedback/VoteMultipleChoice")
	@RequestWrapper(localName = "VoteMultipleChoice", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback", className = "com.pixelatedev.bossmessenger.feedback.VoteMultipleChoice")
	@ResponseWrapper(localName = "VoteMultipleChoiceResponse", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback", className = "com.pixelatedev.bossmessenger.feedback.VoteMultipleChoiceResponse")
	public void voteMultipleChoice(@WebParam(name = "pollId", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback") int pollId, @WebParam(name = "optionId", targetNamespace = "http://pixelatedev.com/bossmessenger/feedback") int optionId);

}
